# Generated by Django 3.1 on 2020-08-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiStepFormModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=222)),
                ('email', models.CharField(max_length=222)),
                ('phone', models.IntegerField(max_length=222)),
                ('date', models.IntegerField(max_length=222)),
                ('month', models.CharField(max_length=222)),
            ],
        ),
    ]
