# Generated by Django 3.1 on 2020-08-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wab1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='date',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='email',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='multistepformmodel',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='multistepformmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='multistepformmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='multistepformmodel',
            name='di',
            field=models.BooleanField(default=False, verbose_name='Diarrhoea'),
        ),
    ]
