# Generated by Django 3.1 on 2020-08-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wab1', '0002_auto_20200823_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistepformmodel',
            name='di',
            field=models.BooleanField(default=False, verbose_name='bprob'),
        ),
    ]
